name: hex
version: 0.1.0.0
github: "eddiejessup/hex"
license: BSD3
author: "Elliot Marsden"
maintainer: "elliot.marsden@gmail.com"
copyright: "Copyright (c) 2017 Elliot Marsden"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/eddiejessup/hex#readme>

dependencies:
- aeson
- ascii
- base
- binary
- bytestring
- containers
- directory
- exceptions
- fast-logger
- generic-optics
- generic-random
- hashable
- mtl
- optics-core
- optics-extra
- optparse-applicative
- parser-combinators
- path
- path-io
- protolude
- text
- time
- transformers
- unordered-containers
- vector

library:
  source-dirs: src

ghc-options:
- -optP-Wno-nonportable-include-path

- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wmissing-deriving-strategies
- -Wunused-packages

# - -Wno-warnings-deprecations
- -O0
- +RTS -A128m -n2m -RTS
- -j

executables:
  hexc:
    main:                Hexc.hs
    source-dirs:         hexc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hex

tests:
  hex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hex
    - hspec

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
