name: hex
version: 0.1.0.0
github: "eddiejessup/hex"
license: BSD3
author: "Elliot Marsden"
maintainer: "elliot.marsden@gmail.com"
copyright: "Copyright (c) 2017 Elliot Marsden"
language: GHC2021

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/eddiejessup/hex#readme>

dependencies:
  - base

library:
  source-dirs: src

  dependencies:
    - ascii
    - bytestring
    - cereal
    - containers
    - effectful
    - effectful-core
    - effectful-th
    - filepath
    - formatting
    - generic-optics
    - groups
    - optics-core
    - optics-extra
    - parser-combinators
    - protolude
    - text
    - time
    - transformers
    - vector
    - witherable

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wmissing-deriving-strategies
  - -Wunused-packages
  - -O0

executables:
  hexc:
    main: Hexc.hs
    source-dirs: hexc
    dependencies:
      - hex
      - bytestring
      - optparse-applicative
      - filepath
      - time

tests:
  hex-test:
    main: test.hs
    source-dirs: test
    dependencies:
      - hex
      - tasty
      - tasty-hunit
      - containers
      - bytestring

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PartialTypeSignatures
  - StrictData
  - TypeFamilies
  - PatternSynonyms
