name: hex
version: 0.1.0.0
github: "eddiejessup/hex"
license: BSD3
author: "Elliot Marsden"
maintainer: "elliot.marsden@gmail.com"
copyright: "Copyright (c) 2017 Elliot Marsden"
language: GHC2021

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/eddiejessup/hex#readme>

dependencies:
  - base
  - bytestring

library:
  source-dirs: src

  dependencies:
    - ascii
    - cereal
    - containers
    - filepath
    - formatting
    - generic-lens-core
    - generic-optics
    - groups
    - mtl
    - optics-core
    - optics-extra
    - text
    - transformers
    - unordered-containers
    - parser-combinators
    - protolude


ghc-options:
- -optP-Wno-nonportable-include-path

- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wmissing-deriving-strategies
- -Wunused-packages

# - -Wno-warnings-deprecations
- -O0
- +RTS -A128m -n2m -RTS
- -j

executables:
  hexc:
    main:                Hexc.hs
    source-dirs:         hexc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hex
    - optparse-applicative

tests:
  hex-test:
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hex
    - tasty
    - tasty-hunit

default-extensions:
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- GADTs
- LambdaCase
- MultiWayIf
- NoImplicitPrelude
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PartialTypeSignatures
- StrictData
- TypeFamilies
- PatternSynonyms
